# Generated by Django 5.0.7 on 2024-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='context',
            field=models.JSONField(null=True),
        ),
    ]
